# This file was automatically generated by passthru.fetch-deps.
# Please dont edit it manually, your changes might get overwritten!
# TODO: This format file is obsolete, consider migrating to JSON.

{ fetchNuGet }:
[
  (fetchNuGet {
    pname = "Blake3";
    version = "1.1.0";
    hash = "sha256-gSXmXolZOlon1UG2miI9bdS1542vGR8EyukwIkqXdoE=";
  })
  (fetchNuGet {
    pname = "Microsoft.AspNetCore.App.Ref";
    version = "3.1.10";
    hash = "sha256-51D1XkqFMPHJzOmt1HQ0Bf1n9K0auwEyxTJuqA/8xHY=";
  })
  (fetchNuGet {
    pname = "Microsoft.AspNetCore.App.Ref";
    version = "5.0.0";
    hash = "sha256-z22ZDldoIlDUYeF9Rje0aVPlYAGKIpdj5wDzn1CW+jQ=";
  })
  (fetchNuGet {
    pname = "Microsoft.AspNetCore.App.Ref";
    version = "6.0.36";
    hash = "sha256-9jDkWbjw/nd8yqdzVTagCuqr6owJ/DUMi4BlUZT4hWU=";
  })
  (fetchNuGet {
    pname = "Microsoft.AspNetCore.App.Ref";
    version = "7.0.20";
    hash = "sha256-OEDXXjQ1HDRPiA4Y1zPr1xUeH6wlzTCJpts+DZL61wI=";
  })
  (fetchNuGet {
    pname = "Microsoft.AspNetCore.App.Ref";
    version = "8.0.11";
    hash = "sha256-dXJ1h1xyeI+lzdoNiYtmLBzkQnHKZcWSksjuo70yp5k=";
  })
  (fetchNuGet {
    pname = "Microsoft.AspNetCore.App.Runtime.linux-arm64";
    version = "3.1.32";
    hash = "sha256-vZkj1OFhojFyl//ZqrbZG3j8rGk/6rwqMhvvR6gWCgI=";
  })
  (fetchNuGet {
    pname = "Microsoft.AspNetCore.App.Runtime.linux-arm64";
    version = "5.0.17";
    hash = "sha256-ELWBHK+1ijGTvq1BsK/vJx/MNqKS8daZgrQ0Tj9+faA=";
  })
  (fetchNuGet {
    pname = "Microsoft.AspNetCore.App.Runtime.linux-arm64";
    version = "6.0.36";
    hash = "sha256-JQULJyF0ivLoUU1JaFfK/HHg+/qzpN7V2RR2Cc+WlQ4=";
  })
  (fetchNuGet {
    pname = "Microsoft.AspNetCore.App.Runtime.linux-arm64";
    version = "7.0.20";
    hash = "sha256-ewal9R6o20GV0R02ylSijVFdWZAbdN8TK1PCc/ltHBQ=";
  })
  (fetchNuGet {
    pname = "Microsoft.AspNetCore.App.Runtime.linux-arm64";
    version = "8.0.11";
    hash = "sha256-Nn9i9gSqdjsSpbuS2U562nUB/nCsMjoGuagoHGTgLks=";
  })
  (fetchNuGet {
    pname = "Microsoft.AspNetCore.App.Runtime.linux-x64";
    version = "3.1.32";
    hash = "sha256-OV3Ie8JGTEwNI4Y6DJFh+ZUrBTwrSdFjEbfljfAwn3s=";
  })
  (fetchNuGet {
    pname = "Microsoft.AspNetCore.App.Runtime.linux-x64";
    version = "5.0.17";
    hash = "sha256-iHn2yGpaL5EM8L7nJJ2aRCIZ+kE98NS+KWUvrWnjzhg=";
  })
  (fetchNuGet {
    pname = "Microsoft.AspNetCore.App.Runtime.linux-x64";
    version = "6.0.36";
    hash = "sha256-zUsVIpV481vMLAXaLEEUpEMA9/f1HGOnvaQnaWdzlyY=";
  })
  (fetchNuGet {
    pname = "Microsoft.AspNetCore.App.Runtime.linux-x64";
    version = "7.0.20";
    hash = "sha256-vq59xMfrET8InzUhkAsbs2xp3ML+SO9POsbwAiYKzkA=";
  })
  (fetchNuGet {
    pname = "Microsoft.AspNetCore.App.Runtime.linux-x64";
    version = "8.0.11";
    hash = "sha256-qY1nMywwCPOXxBQwXLeYaNSvu7wiXIp1fWeY8ThA4QY=";
  })
  (fetchNuGet {
    pname = "Microsoft.AspNetCore.App.Runtime.osx-arm64";
    version = "6.0.36";
    hash = "sha256-2seqZcz0JeUjkzh3QcGa9TcJ4LUafpFjTRk+Nm8T6T0=";
  })
  (fetchNuGet {
    pname = "Microsoft.AspNetCore.App.Runtime.osx-arm64";
    version = "7.0.20";
    hash = "sha256-PHBb0AuRpB8kkQvQJIJSLu5Ub/U2pYA0wMGBarUkS8o=";
  })
  (fetchNuGet {
    pname = "Microsoft.AspNetCore.App.Runtime.osx-arm64";
    version = "8.0.11";
    hash = "sha256-DzJerzIbUYLmMl/EBOcpHcEzO9OuJ+fmbLJ90ADEKL8=";
  })
  (fetchNuGet {
    pname = "Microsoft.AspNetCore.App.Runtime.osx-x64";
    version = "3.1.32";
    hash = "sha256-LD7skhj3ZqIJlgL2VG/1PqPJT7yGQPuSNkduHhQpM7M=";
  })
  (fetchNuGet {
    pname = "Microsoft.AspNetCore.App.Runtime.osx-x64";
    version = "5.0.17";
    hash = "sha256-TdhOyPN+WA27WFd3PLKdsC+bbyNidOiOOuz/WpHDe+M=";
  })
  (fetchNuGet {
    pname = "Microsoft.AspNetCore.App.Runtime.osx-x64";
    version = "6.0.36";
    hash = "sha256-yxLafxiBKkvfkDggPk0P9YZIHBkDJOsFTO7/V9mEHuU=";
  })
  (fetchNuGet {
    pname = "Microsoft.AspNetCore.App.Runtime.osx-x64";
    version = "7.0.20";
    hash = "sha256-+MQMRFzfG2CbNJnfw0buP4VorL2yR+T4UeEBSbKSmPY=";
  })
  (fetchNuGet {
    pname = "Microsoft.AspNetCore.App.Runtime.osx-x64";
    version = "8.0.11";
    hash = "sha256-u74pARiTnPqmdxfxiRyhN3X1VEC95uAQGSAcvy3ReAs=";
  })
  (fetchNuGet {
    pname = "Microsoft.Bcl.AsyncInterfaces";
    version = "5.0.0";
    hash = "sha256-bpJjcJSUSZH0GeOXoZI12xUQOf2SRtxG7sZV0dWS5TI=";
  })
  (fetchNuGet {
    pname = "Microsoft.Bcl.AsyncInterfaces";
    version = "8.0.0";
    hash = "sha256-9aWmiwMJKrKr9ohD1KSuol37y+jdDxPGJct3m2/Bknw=";
  })
  (fetchNuGet {
    pname = "Microsoft.NETCore.App.Host.linux-arm64";
    version = "3.1.32";
    hash = "sha256-V5yVTC2je2wsv/gqLaVmnzcnDfNGETz0e7/M3MG5z/8=";
  })
  (fetchNuGet {
    pname = "Microsoft.NETCore.App.Host.linux-arm64";
    version = "5.0.17";
    hash = "sha256-a8FLTWaNL6TknXDx+YFwLzcDn7nuq3l9yN2UUrHfZx8=";
  })
  (fetchNuGet {
    pname = "Microsoft.NETCore.App.Host.linux-arm64";
    version = "6.0.36";
    hash = "sha256-9lC/LYnthYhjkWWz2kkFCvlA5LJOv11jdt59SDnpdy0=";
  })
  (fetchNuGet {
    pname = "Microsoft.NETCore.App.Host.linux-arm64";
    version = "7.0.20";
    hash = "sha256-/20dMbO1Ft0WVhl+Lv1916Thvr4kPP9LuuX4bKE+czE=";
  })
  (fetchNuGet {
    pname = "Microsoft.NETCore.App.Host.linux-arm64";
    version = "8.0.11";
    hash = "sha256-x8LMZdbVwjhsXwUbjsQKT61Qd7Y1EopoEGDeKRXKipk=";
  })
  (fetchNuGet {
    pname = "Microsoft.NETCore.App.Host.linux-x64";
    version = "3.1.32";
    hash = "sha256-ajR6pZv0zuzWDyxEnWtAuhasV5biV5lvweEbefTISiM=";
  })
  (fetchNuGet {
    pname = "Microsoft.NETCore.App.Host.linux-x64";
    version = "5.0.17";
    hash = "sha256-exMpVamk8ZzfCQDQcDmQDYJplDcOOU99ic7NSDKUgtE=";
  })
  (fetchNuGet {
    pname = "Microsoft.NETCore.App.Host.linux-x64";
    version = "6.0.36";
    hash = "sha256-VFRDzx7LJuvI5yzKdGmw/31NYVbwHWPKQvueQt5xc10=";
  })
  (fetchNuGet {
    pname = "Microsoft.NETCore.App.Host.linux-x64";
    version = "7.0.20";
    hash = "sha256-Y1Dg8Sqhya86xD+9aJOuznT4mJUyFmoF/YZc0+5LBdc=";
  })
  (fetchNuGet {
    pname = "Microsoft.NETCore.App.Host.linux-x64";
    version = "8.0.11";
    hash = "sha256-brt8CP11GH1hidrkYbAou8mMQ6kr2eStr/oqesK6AnY=";
  })
  (fetchNuGet {
    pname = "Microsoft.NETCore.App.Host.osx-arm64";
    version = "6.0.36";
    hash = "sha256-DaSWwYACJGolEBuMhzDVCj/rQTdDt061xCVi+gyQnuo=";
  })
  (fetchNuGet {
    pname = "Microsoft.NETCore.App.Host.osx-arm64";
    version = "7.0.20";
    hash = "sha256-MTyRTWhDmMaCsNorju/tLb0w+ssKydDX/NBFzSfqB0Q=";
  })
  (fetchNuGet {
    pname = "Microsoft.NETCore.App.Host.osx-arm64";
    version = "8.0.11";
    hash = "sha256-o7AS58dmjN8MwwI1TTQ9H36cKjJ08MPfXXcCtblE2Cw=";
  })
  (fetchNuGet {
    pname = "Microsoft.NETCore.App.Host.osx-x64";
    version = "3.1.32";
    hash = "sha256-AOr3qBlvr+WGF79tTq/yvKWJLXqEO4Sv+eTCpZGVz6A=";
  })
  (fetchNuGet {
    pname = "Microsoft.NETCore.App.Host.osx-x64";
    version = "5.0.17";
    hash = "sha256-bDgVacWuwDTJqEL/RbZ2gS9EGexx0OGZsYPnHQPh5Qk=";
  })
  (fetchNuGet {
    pname = "Microsoft.NETCore.App.Host.osx-x64";
    version = "6.0.36";
    hash = "sha256-FrRny9EI6HKCKQbu6mcLj5w4ooSRrODD4Vj2ZMGnMd4=";
  })
  (fetchNuGet {
    pname = "Microsoft.NETCore.App.Host.osx-x64";
    version = "7.0.20";
    hash = "sha256-DdumMpP5QN0rPDsB8sjxACM13mT7Wbb0w3LaCe96twc=";
  })
  (fetchNuGet {
    pname = "Microsoft.NETCore.App.Host.osx-x64";
    version = "8.0.11";
    hash = "sha256-O0U9c06Cdl6nEtmUFB3qoSMi2GcFEdVWLFwqED10APU=";
  })
  (fetchNuGet {
    pname = "Microsoft.NETCore.App.Ref";
    version = "3.1.0";
    hash = "sha256-nuAvHwmJ2s3Ob1qNDH1+uV3awOZaWlaV3FenTmPUWyM=";
  })
  (fetchNuGet {
    pname = "Microsoft.NETCore.App.Ref";
    version = "5.0.0";
    hash = "sha256-kQ8wpR4crWoqy/jrskat34Y3Nr3nbxoSpEPMnxycwtw=";
  })
  (fetchNuGet {
    pname = "Microsoft.NETCore.App.Ref";
    version = "6.0.36";
    hash = "sha256-9LZgVoIFF8qNyUu8kdJrYGLutMF/cL2K82HN2ywwlx8=";
  })
  (fetchNuGet {
    pname = "Microsoft.NETCore.App.Ref";
    version = "7.0.20";
    hash = "sha256-W9RU3bja4BQLAbsaIhANQPJJh6DycDiBR+WZ3mK6Zrs=";
  })
  (fetchNuGet {
    pname = "Microsoft.NETCore.App.Ref";
    version = "8.0.11";
    hash = "sha256-lo6MAnvFQ1DBDh+9qdxzOJMgACsvFjj2e5bhreJ4v0I=";
  })
  (fetchNuGet {
    pname = "Microsoft.NETCore.App.Runtime.linux-arm64";
    version = "3.1.32";
    hash = "sha256-eL+GH7cDWSzXPPN9yxQvQ6IQ3AFUfnH0OJ/r8Mmx7I4=";
  })
  (fetchNuGet {
    pname = "Microsoft.NETCore.App.Runtime.linux-arm64";
    version = "5.0.17";
    hash = "sha256-2KU5RRHGbkCA+lCEH5QaBHma1AZqVLWBws7IKxBWkJs=";
  })
  (fetchNuGet {
    pname = "Microsoft.NETCore.App.Runtime.linux-arm64";
    version = "6.0.36";
    hash = "sha256-k3rxvUhCEU0pVH8KgEMtkPiSOibn+nBh+0zT2xIfId8=";
  })
  (fetchNuGet {
    pname = "Microsoft.NETCore.App.Runtime.linux-arm64";
    version = "7.0.20";
    hash = "sha256-TemMvbNrDzJVHWwxVgnNN2CnTyI6TcvvZDpF4ts6IAw=";
  })
  (fetchNuGet {
    pname = "Microsoft.NETCore.App.Runtime.linux-arm64";
    version = "8.0.11";
    hash = "sha256-kwfUZm1hnsikJdpgTNDObdNL54wPO80TYtdNNlzfh54=";
  })
  (fetchNuGet {
    pname = "Microsoft.NETCore.App.Runtime.linux-x64";
    version = "3.1.32";
    hash = "sha256-h4HjfRnvH81dW84S3TCPcCfxeQLiLN7b1ZleRNsprFY=";
  })
  (fetchNuGet {
    pname = "Microsoft.NETCore.App.Runtime.linux-x64";
    version = "5.0.17";
    hash = "sha256-2NpVvrbqct3M1fKiSe/zyt41mf1aV6WUdxIlJod27Ek=";
  })
  (fetchNuGet {
    pname = "Microsoft.NETCore.App.Runtime.linux-x64";
    version = "6.0.36";
    hash = "sha256-U8wJ2snSDFqeAgDVLXjnniidC7Cr5aJ1/h/BMSlyu0c=";
  })
  (fetchNuGet {
    pname = "Microsoft.NETCore.App.Runtime.linux-x64";
    version = "7.0.20";
    hash = "sha256-L+WaGvoXVMT3tZ7R5xFE06zaLcC3SI7LEf4ATBkUAGQ=";
  })
  (fetchNuGet {
    pname = "Microsoft.NETCore.App.Runtime.linux-x64";
    version = "8.0.11";
    hash = "sha256-V55LsR6DmpxARdnZvqoYakebdJ+2cZykTMDThrmQnA0=";
  })
  (fetchNuGet {
    pname = "Microsoft.NETCore.App.Runtime.osx-arm64";
    version = "6.0.36";
    hash = "sha256-UfLcrL2Gj/OLz0s92Oo+OCJeDpZFAcQLPLiSNND8D5Y=";
  })
  (fetchNuGet {
    pname = "Microsoft.NETCore.App.Runtime.osx-arm64";
    version = "7.0.20";
    hash = "sha256-VHmF1/ObK5hxGYvm5/+pTdketHnxxcnAGK5RaTQpVqE=";
  })
  (fetchNuGet {
    pname = "Microsoft.NETCore.App.Runtime.osx-arm64";
    version = "8.0.11";
    hash = "sha256-NxiVGeu54YKpQSKqVFVLSDD90ZDFykj/KBGYUCym6PM=";
  })
  (fetchNuGet {
    pname = "Microsoft.NETCore.App.Runtime.osx-x64";
    version = "3.1.32";
    hash = "sha256-IcJ45kU65HpYu1EjMB1sf87PTSvPdS2h5uyIzX4acxk=";
  })
  (fetchNuGet {
    pname = "Microsoft.NETCore.App.Runtime.osx-x64";
    version = "5.0.17";
    hash = "sha256-V1arT33a215ZP+Jo/vkrhko78FsA8X8XujZ6jUKfBd4=";
  })
  (fetchNuGet {
    pname = "Microsoft.NETCore.App.Runtime.osx-x64";
    version = "6.0.36";
    hash = "sha256-0xIJYFzxdMcnCj3wzkFRQZSnQcPHzPHMzePRIOA3oJs=";
  })
  (fetchNuGet {
    pname = "Microsoft.NETCore.App.Runtime.osx-x64";
    version = "7.0.20";
    hash = "sha256-yktNSySitxWbO6LjcxUuewWFMF2EbcoM2w18CqxmVlc=";
  })
  (fetchNuGet {
    pname = "Microsoft.NETCore.App.Runtime.osx-x64";
    version = "8.0.11";
    hash = "sha256-6HdptW7Wf1fZ8L3sUEpEvRtz5XCRSEcGAwpzVKtOy+o=";
  })
  (fetchNuGet {
    pname = "Microsoft.NETFramework.ReferenceAssemblies";
    version = "1.0.3";
    hash = "sha256-FBoJP5DHZF0QHM0xLm9yd4HJZVQOuSpSKA+VQRpphEE=";
  })
  (fetchNuGet {
    pname = "Microsoft.NETFramework.ReferenceAssemblies.net20";
    version = "1.0.3";
    hash = "sha256-f3SZf+wzjd5w9ajJ/Qmqb+IShnMeexM8wTPWROTjxeg=";
  })
  (fetchNuGet {
    pname = "Microsoft.NETFramework.ReferenceAssemblies.net35";
    version = "1.0.3";
    hash = "sha256-sWFWERqIZw2Rp1f71GX8tIVuA0saTVI64sQaRw81ePk=";
  })
  (fetchNuGet {
    pname = "Microsoft.NETFramework.ReferenceAssemblies.net40";
    version = "1.0.3";
    hash = "sha256-VNbiChthyveTldbXHQkSZegfWlcFrErlKvRcoUPDxpQ=";
  })
  (fetchNuGet {
    pname = "Microsoft.NETFramework.ReferenceAssemblies.net452";
    version = "1.0.3";
    hash = "sha256-RTPuFG8D7gnwINEoEtAqmVm4oTW8K4Z87v1o4DDeLMI=";
  })
  (fetchNuGet {
    pname = "Microsoft.NETFramework.ReferenceAssemblies.net462";
    version = "1.0.3";
    hash = "sha256-7mkqhFdDUAkQhV1MMwym6e+HwW4W90DkR00YcYXWbiE=";
  })
  (fetchNuGet {
    pname = "Microsoft.NETFramework.ReferenceAssemblies.net472";
    version = "1.0.3";
    hash = "sha256-/6ClVwo5+RE5kWTQWB/93vmbXj37ql8iDlziKWm89Xw=";
  })
  (fetchNuGet {
    pname = "Microsoft.NETFramework.ReferenceAssemblies.net48";
    version = "1.0.3";
    hash = "sha256-in40hTjn65E1FpaRFon0nj1PY/i6tRdDK74Vm4sRBKI=";
  })
  (fetchNuGet {
    pname = "MinAsyncBridge";
    version = "0.12.4";
    hash = "sha256-xwSVf3cFCON8TtETLuRG6DF3t/YvQRFhwxP9nC74Efc=";
  })
  (fetchNuGet {
    pname = "MinThreadingBridge";
    version = "0.11.4";
    hash = "sha256-ARmKOV8mDSt3nY0hKN0XZeqe7nTHI/BLNU4eVWXTPXU=";
  })
  (fetchNuGet {
    pname = "Net35.Actions";
    version = "1.1.0";
    hash = "sha256-Hm2altpaOFQYLozHk3FMHQ3w8ehcirmUP6sqVD7JBnE=";
  })
  (fetchNuGet {
    pname = "NetLegacySupport.Numerics";
    version = "1.0.1";
    hash = "sha256-GTHKSXn6d6l2bLL373ZSIr4Z40pQZ4Cli9JFCxXXY+w=";
  })
  (fetchNuGet {
    pname = "Newtonsoft.Json";
    version = "13.0.3";
    hash = "sha256-hy/BieY4qxBWVVsDqqOPaLy1QobiIapkbrESm6v2PHc=";
  })
  (fetchNuGet {
    pname = "OpenMcdf";
    version = "2.3.1";
    hash = "sha256-7Mjp7oAQCy+X/UG/40NzzDdYho3CbOd0HW2w0bE21QI=";
  })
  (fetchNuGet {
    pname = "SabreTools.ASN1";
    version = "1.5.1";
    hash = "sha256-J6Iw44x6DGSAWmo4q1+sTrkcIc41eEBjChYNdazhvwM=";
  })
  (fetchNuGet {
    pname = "SabreTools.Compression";
    version = "0.6.3";
    hash = "sha256-ZgoJzy7QpIl5Qqlk8O4DYXpV6kIaf04zStaV8SvzJNE=";
  })
  (fetchNuGet {
    pname = "SabreTools.Hashing";
    version = "1.4.1";
    hash = "sha256-tCOMMhRtdW16NWi7fCkqXWls5Tb108LawDjWAqBIaLg=";
  })
  (fetchNuGet {
    pname = "SabreTools.IO";
    version = "1.6.2";
    hash = "sha256-RrSr9yGfqUGIu5iG0AAv0MwZ2/+9a/2XNYaPOPFsNzM=";
  })
  (fetchNuGet {
    pname = "SabreTools.Matching";
    version = "1.5.1";
    hash = "sha256-YrcdBXJKFfoD3+S4XkoAUH4LhN1rPk5DMY6z9UwTXQ8=";
  })
  (fetchNuGet {
    pname = "SabreTools.Models";
    version = "1.5.8";
    hash = "sha256-6Erd8nBwLVK3KVmZPAH2P58NQbinCMW98gveqoo1WL8=";
  })
  (fetchNuGet {
    pname = "SabreTools.Serialization";
    version = "1.8.4";
    hash = "sha256-LjtX79eJGeD1Bz+SWeZP/8BMGo+ZEHNnLEa3MQ2d3rU=";
  })
  (fetchNuGet {
    pname = "SabreTools.Serialization";
    version = "1.8.6";
    hash = "sha256-zJRpTturGPiFSm05XMxOEg5G1gdT05VhuLgNyikXLBM=";
  })
  (fetchNuGet {
    pname = "SharpCompress";
    version = "0.38.0";
    hash = "sha256-bQL3kazuqbuqn+Csy9RYMMUsNMtqkGXF7x32s787UBM=";
  })
  (fetchNuGet {
    pname = "System.Buffers";
    version = "4.5.1";
    hash = "sha256-wws90sfi9M7kuCPWkv1CEYMJtCqx9QB/kj0ymlsNaxI=";
  })
  (fetchNuGet {
    pname = "System.IO.Hashing";
    version = "8.0.0";
    hash = "sha256-szOGt0TNBo6dEdC3gf6H+e9YW3Nw0woa6UnCGGGK5cE=";
  })
  (fetchNuGet {
    pname = "System.Memory";
    version = "4.5.5";
    hash = "sha256-EPQ9o1Kin7KzGI5O3U3PUQAZTItSbk9h/i4rViN3WiI=";
  })
  (fetchNuGet {
    pname = "System.Numerics.Vectors";
    version = "4.5.0";
    hash = "sha256-qdSTIFgf2htPS+YhLGjAGiLN8igCYJnCCo6r78+Q+c8=";
  })
  (fetchNuGet {
    pname = "System.Runtime.CompilerServices.Unsafe";
    version = "4.5.3";
    hash = "sha256-lnZMUqRO4RYRUeSO8HSJ9yBHqFHLVbmenwHWkIU20ak=";
  })
  (fetchNuGet {
    pname = "System.Runtime.CompilerServices.Unsafe";
    version = "6.0.0";
    hash = "sha256-bEG1PnDp7uKYz/OgLOWs3RWwQSVYm+AnPwVmAmcgp2I=";
  })
  (fetchNuGet {
    pname = "System.Text.Encoding.CodePages";
    version = "8.0.0";
    hash = "sha256-fjCLQc1PRW0Ix5IZldg0XKv+J1DqPSfu9pjMyNBp7dE=";
  })
  (fetchNuGet {
    pname = "System.Threading.Tasks.Extensions";
    version = "4.5.4";
    hash = "sha256-owSpY8wHlsUXn5xrfYAiu847L6fAKethlvYx97Ri1ng=";
  })
  (fetchNuGet {
    pname = "UnshieldSharp";
    version = "1.9.4";
    hash = "sha256-ie1OBWmOYoAx0u8gzUj+ay/K/h96XessaGMsxRlI6WM=";
  })
  (fetchNuGet {
    pname = "WiseUnpacker";
    version = "1.5.6";
    hash = "sha256-zsAEUN1/4mdl+J2Vk8kA/1XXzomiMQ72hjHgndB6ZrY=";
  })
  (fetchNuGet {
    pname = "ZstdSharp.Port";
    version = "0.8.1";
    hash = "sha256-PeQvyz3lUrK+t+n1dFtNXCLztQtAfkqUuM6mOqBZHLg=";
  })
]
